-- MySQL Script generated by MySQL Workbench
-- 05/09/15 18:03:22
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema afmps
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `afmps` DEFAULT CHARACTER SET utf8 ;
USE `afmps` ;

-- -----------------------------------------------------
-- Table `afmps`.`medicament`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `afmps`.`medicament` (
  `mID` VARCHAR(6) NOT NULL,
  `nom` VARCHAR(250) NULL DEFAULT NULL,
  `mah` VARCHAR(200) NULL DEFAULT NULL,
  `generic` VARCHAR(1) NULL DEFAULT NULL,
  `pack_size` LONGTEXT NULL DEFAULT NULL,
  `PharmFormFr` VARCHAR(200) NULL DEFAULT NULL,
  `PackFr` VARCHAR(255) NULL DEFAULT NULL,
  `DelivFr` VARCHAR(255) NULL DEFAULT NULL,
  `ActSubsts` LONGTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`mID`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `afmps`.`patient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `afmps`.`patient` (
  `eID` INT(11) NOT NULL,
  `nom` VARCHAR(100) NULL DEFAULT NULL,
  `prenom` VARCHAR(100) NULL DEFAULT NULL,
  `adresse` VARCHAR(250) NULL DEFAULT NULL,
  `date_de_naissance` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`eID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `afmps`.`prescription`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `afmps`.`prescription` (
  `pID` INT(11) NOT NULL,
  `mID` VARCHAR(6) NULL DEFAULT NULL,
  `posologie` VARCHAR(250) NULL DEFAULT NULL,
  `date_prescription` DATE NULL DEFAULT NULL,
  `date_delivrance` DATE NULL DEFAULT NULL,
  `delivre` TINYINT(1) NULL DEFAULT NULL,
  `eID` INT(11) NULL DEFAULT NULL,
  `inami` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`pID`),
  INDEX `lien_prescription_patient_idx` (`eID` ASC),
  INDEX `lien_prescription_medicament_idx` (`mID` ASC),
  CONSTRAINT `lien_prescription_medicament`
    FOREIGN KEY (`mID`)
    REFERENCES `afmps`.`medicament` (`mID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `lien_prescription_patient`
    FOREIGN KEY (`eID`)
    REFERENCES `afmps`.`patient` (`eID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
