/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projet_sim_2;

import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.awt.event.WindowEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.KeyStroke;

/**
 *
 * @author philo
 */

public class fPharmStock extends javax.swing.JDialog {

    /**
     * A return status code - returned if Cancel button has been pressed
     */
    public static final int RET_CANCEL = 0;
    /**
     * A return status code - returned if OK button has been pressed
     */
    public static final int RET_OK = 1;

    /**
     * Creates new form fPharmAccueil
     */
    
    /**
     * Creates new form fPharmPrescription
     */
    private patient patient;
    private prescription prescription;
    private medicament medicament;
    private interactionBaseDonnees base;
    private ResultSetTableModel tableModel;
    private ArrayList <prescription> liste_prescription;
        
    
    
    public fPharmStock(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setTitle("Stock du pharmacien");
        
        this.patient = null;
        this.prescription = null;
        this.medicament = null;
        this.base = new interactionBaseDonnees();
        
       
       this.setResizable(true);
       
       this.tableModel = new ResultSetTableModel();
       this.tableMedicament.setModel(this.tableModel);
       //this.tableModel.setResultSet(this.getAllPrescription(this.patient.geteID()));
       

        // Close the dialog when Esc is pressed
        String cancelName = "cancel";
        InputMap inputMap = getRootPane().getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), cancelName);
        ActionMap actionMap = getRootPane().getActionMap();
        actionMap.put(cancelName, new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                doClose(RET_CANCEL);
            }
        });
    }
    
    //a modifier
    /*public ResultSet getAllMedicament() throws SQLException{
        String sql = "SELECT p.pID, p.date_prescription, p.date_delivrance, p.delivre,  m.nom, m.mID,  m.quantite, p.posologie, m.generic, m.mah, m.pack_size, m.PharmFormFr, m.PackFr, m.DelivFr, m.ActSubsts  FROM prescription AS p, medicament AS m WHERE p.eID = ? AND p.mID=m.mID";
        PreparedStatement ps;
        java.sql.Connection c = projet_sim_2.Connection.getInstance().getConn();
        ps = c.prepareStatement(sql);
        ps.setLong(1, this.patient.geteID());
        ResultSet resultat = ps.executeQuery();
        return resultat;
    }*/

    //a modifier
    /*public boolean generique() throws SQLException{
        String sql = "SELECT delivre FROM prescription WHERE eID = ? AND delivre = 0";
        PreparedStatement ps;
        java.sql.Connection c = projet_sim_2.Connection.getInstance().getConn();
        ps = c.prepareStatement(sql);
        ps.setLong(1, this.patient.geteID());
        ResultSet resultat = ps.executeQuery();
        return resultat.next();
    }*/
            
    
    /**
     * @return the return status of this dialog - one of RET_OK or RET_CANCEL
     */
    public int getReturnStatus() {
        return returnStatus;
    }
    
    private void refresh(){  
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonModifier = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        scrolePanelTable = new javax.swing.JScrollPane();
        tableMedicament = new javax.swing.JTable();
        textFieldMedicament = new javax.swing.JTextField();
        labelMedicament = new javax.swing.JLabel();
        buttonGenerique = new javax.swing.JButton();
        buttonOriginaux = new javax.swing.JButton();
        buttonTout = new javax.swing.JButton();
        labelQuantite = new javax.swing.JLabel();
        spinnerQuantite = new javax.swing.JSpinner();
        labelActSub = new javax.swing.JLabel();
        testFieldActSub = new javax.swing.JTextField();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        buttonModifier.setText("Modifier");
        buttonModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonModifierActionPerformed(evt);
            }
        });

        cancelButton.setText("Fermer");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        tableMedicament.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        scrolePanelTable.setViewportView(tableMedicament);

        textFieldMedicament.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldMedicamentActionPerformed(evt);
            }
        });

        labelMedicament.setText("Médicament:");

        buttonGenerique.setText("Génériques");
        buttonGenerique.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGeneriqueActionPerformed(evt);
            }
        });

        buttonOriginaux.setText("Originaux");

        buttonTout.setText("Tout");
        buttonTout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonToutActionPerformed(evt);
            }
        });

        labelQuantite.setText("quantité");

        labelActSub.setText("Substance active");

        testFieldActSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testFieldActSubActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(scrolePanelTable, javax.swing.GroupLayout.PREFERRED_SIZE, 1243, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(labelQuantite)
                        .addGap(18, 18, 18)
                        .addComponent(spinnerQuantite, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(buttonModifier, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(639, 639, 639)
                        .addComponent(cancelButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(labelMedicament)
                        .addGap(18, 18, 18)
                        .addComponent(textFieldMedicament, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82)
                        .addComponent(labelActSub)
                        .addGap(28, 28, 28)
                        .addComponent(testFieldActSub, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(buttonOriginaux)
                        .addGap(96, 96, 96)
                        .addComponent(buttonGenerique)
                        .addGap(162, 162, 162)
                        .addComponent(buttonTout)))
                .addContainerGap(977, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldMedicament, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelMedicament)
                    .addComponent(labelActSub)
                    .addComponent(testFieldActSub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonTout)
                    .addComponent(buttonOriginaux)
                    .addComponent(buttonGenerique))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrolePanelTable, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelQuantite)
                    .addComponent(spinnerQuantite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonModifier))
                .addGap(18, 18, 18)
                .addComponent(cancelButton)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        getRootPane().setDefaultButton(buttonModifier);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonModifierActionPerformed
      this.refresh();
    }//GEN-LAST:event_buttonModifierActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        doClose(RET_CANCEL);
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(RET_CANCEL);
    }//GEN-LAST:event_closeDialog

    private void textFieldMedicamentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldMedicamentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldMedicamentActionPerformed

    private void buttonGeneriqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGeneriqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonGeneriqueActionPerformed

    private void buttonToutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonToutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonToutActionPerformed

    private void testFieldActSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testFieldActSubActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_testFieldActSubActionPerformed

        
    private void doClose(int retStatus) {
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fPharmPrescription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fPharmPrescription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fPharmPrescription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fPharmPrescription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                fPharmPrescription dialog = new fPharmPrescription(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonGenerique;
    private javax.swing.JButton buttonModifier;
    private javax.swing.JButton buttonOriginaux;
    private javax.swing.JButton buttonTout;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel labelActSub;
    private javax.swing.JLabel labelMedicament;
    private javax.swing.JLabel labelQuantite;
    private javax.swing.JScrollPane scrolePanelTable;
    private javax.swing.JSpinner spinnerQuantite;
    private javax.swing.JTable tableMedicament;
    private javax.swing.JTextField testFieldActSub;
    private javax.swing.JTextField textFieldMedicament;
    // End of variables declaration//GEN-END:variables

    private int returnStatus = RET_CANCEL;
}
